server:
  port: 9527
spring:
  application:
    name: cloud-nacosgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名进行路由
      routes:
        - id: payment_rounth #路由的ID,没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost #匹配后提供服务的路由地址
          uri:  lb://order-service #lb开启负载均衡
          predicates:
            - Path=/order/** #断言，路径匹配的进行路由
          # filters: #过滤器


